# Generated by Django 2.2.5 on 2020-02-03 06:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20200202_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
