# Generated by Django 2.2.5 on 2020-02-22 10:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_auto_20200203_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='finished_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='task',
            name='plan_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 22, 10, 54, 51, 429634, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
