# Generated by Django 2.2.5 on 2019-11-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=255)),
                ('type', models.IntegerField(default=0)),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'axe_resource',
            },
        ),
    ]
