# Generated by Django 2.2.5 on 2020-02-02 10:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancestor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
